name: RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP and Create User
        run: |
          # 1. إنشاء حساب المسؤول
          net user kamel123 MyStrong123 /add
          net localgroup administrators kamel123 /add
          
          # 2. تفعيل خدمة سطح المكتب عن بعد وفتح جدار الحماية
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start TCP Tunnel via Bore
        run: |
          # 1. تحميل أداة Bore وتجهيزها
          Invoke-WebRequest https://github.com/ekzhang/bore/releases/download/v0.5.1/bore-v0.5.1-x86_64-pc-windows-msvc.zip -OutFile bore.zip
          Expand-Archive -Path bore.zip -DestinationPath . -Force
          
          # 2. فتح نفق مباشر لمنفذ الـ RDP نحو سيرفر Bore العام
          ./bore.exe local 3389 --to bore.pub
